#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class BaseDatosARkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFrases(Frases instance);
    partial void UpdateFrases(Frases instance);
    partial void DeleteFrases(Frases instance);
    partial void InsertAlerta(Alerta instance);
    partial void UpdateAlerta(Alerta instance);
    partial void DeleteAlerta(Alerta instance);
    #endregion
		
		public BaseDatosARkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		
		
		public BaseDatosARkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		
		
		public System.Data.Linq.Table<Frases> Frases
		{
			get
			{
				return this.GetTable<Frases>();
			}
		}
		
		public System.Data.Linq.Table<Alerta> Alerta
		{
			get
			{
				return this.GetTable<Alerta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Frases : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Amistad;
		
		private string _Identificador;
		
		private string _Recetas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAmistadChanging(string value);
    partial void OnAmistadChanged();
    partial void OnIdentificadorChanging(string value);
    partial void OnIdentificadorChanged();
    partial void OnRecetasChanging(string value);
    partial void OnRecetasChanged();
    #endregion
		
		public Frases()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amistad", CanBeNull=false)]
		public string Amistad
		{
			get
			{
				return this._Amistad;
			}
			set
			{
				if ((this._Amistad != value))
				{
					this.OnAmistadChanging(value);
					this.SendPropertyChanging();
					this._Amistad = value;
					this.SendPropertyChanged("Amistad");
					this.OnAmistadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", CanBeNull=false, IsPrimaryKey=true)]
		public string Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recetas", CanBeNull=false)]
		public string Recetas
		{
			get
			{
				return this._Recetas;
			}
			set
			{
				if ((this._Recetas != value))
				{
					this.OnRecetasChanging(value);
					this.SendPropertyChanging();
					this._Recetas = value;
					this.SendPropertyChanged("Recetas");
					this.OnRecetasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Alerta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FechaFrase;
		
		private string _HoraAlertas;
		
		private string _Identificador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFechaFraseChanging(string value);
    partial void OnFechaFraseChanged();
    partial void OnHoraAlertasChanging(string value);
    partial void OnHoraAlertasChanged();
    partial void OnIdentificadorChanging(string value);
    partial void OnIdentificadorChanged();
    #endregion
		
		public Alerta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFrase", CanBeNull=false)]
		public string FechaFrase
		{
			get
			{
				return this._FechaFrase;
			}
			set
			{
				if ((this._FechaFrase != value))
				{
					this.OnFechaFraseChanging(value);
					this.SendPropertyChanging();
					this._FechaFrase = value;
					this.SendPropertyChanged("FechaFrase");
					this.OnFechaFraseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraAlertas", CanBeNull=false)]
		public string HoraAlertas
		{
			get
			{
				return this._HoraAlertas;
			}
			set
			{
				if ((this._HoraAlertas != value))
				{
					this.OnHoraAlertasChanging(value);
					this.SendPropertyChanging();
					this._HoraAlertas = value;
					this.SendPropertyChanged("HoraAlertas");
					this.OnHoraAlertasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", CanBeNull=false, IsPrimaryKey=true)]
		public string Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
